### ISSUE TITLE
You Cannot Hold Non-Existent Permissions 

### ISSUE THREAD

**Issue by QuickBrownFoxy** [anthonycr/Grant#5]
Can you check this? https://commonsware.com/blog/2015/11/09/you-cannot-hold-nonexistent-permissions.html Can this be part of the library or should I check it myself?

**Comment by anthonycr** [comment]
Yes, I've started work on it in this commit: https://github.com/anthonycr/Grant/commit/4a6d690b3db5f9494c240db666d119b0380d60ab

Current plan is to use reflection when the manager is initialized in order to determine what permissions are available to the app, there's a small initial performance hit when constructing the manager that I will have to figure out a workaround for (probably thread it and queue actions until it's complete). If you request a permission that does not exist, e.g. request READ_STORAGE on API < 16, then it will be able to determine that it should NOT check for permission, but instead fire off another event permissionDoesNotExist(String permission) which by default will grant you the permission - the idea is that most permissions are regressive in that the restrict something that was formerly allowed. If that is not the case then the permissionDoesNotExist event will be able to be overridden and you will be able to do something else.

**Comment by anthonycr** [comment]
Fixed in https://github.com/anthonycr/Grant/releases/tag/v1.1.1

No usage change is necessary on your end. There is an optional method that can be overridden to return false in the PermissionsResultAction class if you don't want non-existent permissions to be automatically granted on older API versions.
